export type Patient = {
  patient_id: string;
  esi: number;
  age: number;
  arrivalmode: number;
  arrivalhour_bin: number;
  insurance_status: number;
  n_edvisits: number;
  n_admissions: number;
  triage_vital_hr: number;
  triage_vital_sbp: number;
  triage_vital_rr: number;
  triage_vital_o2: number;
  triage_vital_temp: number;
  cc_chestpain: number;
  cc_shortnessofbreath: number;
  cc_alteredmentalstatus: number;
  disposition: number;
  arrival_timestamp: string;
  time_in_ed_minutes: number;
  current_status: 'waiting' | 'being_seen';
  predicted_admission_risk: number;
  risk_level: 'Low' | 'High' | 'Medium';
  recommended_priority_rank: number;
  bed_no: number | null;
};

export const patients: Patient[] = [
  { patient_id: 'ED001', esi: 4, age: 40, arrivalmode: 6, arrivalhour_bin: 1, insurance_status: 4, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 63, triage_vital_sbp: 146, triage_vital_rr: 18, triage_vital_o2: 97, triage_vital_temp: 97, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 01:00', time_in_ed_minutes: 1020, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 24, bed_no: null },
  { patient_id: 'ED002', esi: 2, age: 66, arrivalmode: 6, arrivalhour_bin: 4, insurance_status: 1, n_edvisits: 1, n_admissions: 0, triage_vital_hr: 78, triage_vital_sbp: 134, triage_vital_rr: 16, triage_vital_o2: 97, triage_vital_temp: 97.8, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 10:00', time_in_ed_minutes: 480, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 30, bed_no: null },
  { patient_id: 'ED003', esi: 3, age: 84, arrivalmode: 6, arrivalhour_bin: 3, insurance_status: 3, n_edvisits: 1, n_admissions: 0, triage_vital_hr: 101, triage_vital_sbp: 133, triage_vital_rr: 18, triage_vital_o2: 97, triage_vital_temp: 98.4, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 1, arrival_timestamp: '04-01-2026 07:00', time_in_ed_minutes: 660, current_status: 'being_seen', predicted_admission_risk: 0.8, risk_level: 'High', recommended_priority_rank: 3, bed_no: 1 },
  { patient_id: 'ED004', esi: 3, age: 86, arrivalmode: 6, arrivalhour_bin: 5, insurance_status: 3, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 76, triage_vital_sbp: 143, triage_vital_rr: 18, triage_vital_o2: 98, triage_vital_temp: 98.5, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 13:00', time_in_ed_minutes: 300, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 33, bed_no: null },
  { patient_id: 'ED005', esi: 4, age: 87, arrivalmode: 2, arrivalhour_bin: 4, insurance_status: 3, n_edvisits: 2, n_admissions: 1, triage_vital_hr: 88, triage_vital_sbp: 155, triage_vital_rr: 17, triage_vital_o2: 98, triage_vital_temp: 97.8, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 10:00', time_in_ed_minutes: 480, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 31, bed_no: null },
  { patient_id: 'ED006', esi: 2, age: 52, arrivalmode: 6, arrivalhour_bin: 5, insurance_status: 4, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 89, triage_vital_sbp: 162, triage_vital_rr: 18, triage_vital_o2: 98, triage_vital_temp: 97.9, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 13:00', time_in_ed_minutes: 300, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 34, bed_no: null },
  { patient_id: 'ED007', esi: 2, age: 53, arrivalmode: 6, arrivalhour_bin: 4, insurance_status: 3, n_edvisits: 4, n_admissions: 3, triage_vital_hr: 118, triage_vital_sbp: 105, triage_vital_rr: 20, triage_vital_o2: 98, triage_vital_temp: 97.5, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 1, arrival_timestamp: '04-01-2026 10:00', time_in_ed_minutes: 480, current_status: 'being_seen', predicted_admission_risk: 0.8, risk_level: 'High', recommended_priority_rank: 6, bed_no: 2 },
  { patient_id: 'ED008', esi: 4, age: 49, arrivalmode: 2, arrivalhour_bin: 6, insurance_status: 2, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 103, triage_vital_sbp: 155, triage_vital_rr: 16, triage_vital_o2: 98, triage_vital_temp: 98.2, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 16:00', time_in_ed_minutes: 120, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 40, bed_no: null },
  { patient_id: 'ED009', esi: 2, age: 50, arrivalmode: 2, arrivalhour_bin: 1, insurance_status: 2, n_edvisits: 1, n_admissions: 0, triage_vital_hr: 116, triage_vital_sbp: 210, triage_vital_rr: 18, triage_vital_o2: 97, triage_vital_temp: 97.1, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 01:00', time_in_ed_minutes: 1020, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 25, bed_no: null },
  { patient_id: 'ED010', esi: 2, age: 51, arrivalmode: 2, arrivalhour_bin: 4, insurance_status: 2, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 163, triage_vital_sbp: 177, triage_vital_rr: 20, triage_vital_o2: 96, triage_vital_temp: 97, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 1, arrival_timestamp: '04-01-2026 10:00', time_in_ed_minutes: 480, current_status: 'being_seen', predicted_admission_risk: 0.8, risk_level: 'High', recommended_priority_rank: 1, bed_no: 3 },
  { patient_id: 'ED011', esi: 3, age: 45, arrivalmode: 2, arrivalhour_bin: 4, insurance_status: 2, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 90.5, triage_vital_sbp: 119, triage_vital_rr: 17, triage_vital_o2: 98, triage_vital_temp: 97.95, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 10:00', time_in_ed_minutes: 480, current_status: 'being_seen', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 32, bed_no: 4 },
  { patient_id: 'ED012', esi: 2, age: 45, arrivalmode: 6, arrivalhour_bin: 5, insurance_status: 2, n_edvisits: 1, n_admissions: 0, triage_vital_hr: 142, triage_vital_sbp: 129, triage_vital_rr: 24, triage_vital_o2: 97, triage_vital_temp: 99.1, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 13:00', time_in_ed_minutes: 300, current_status: 'being_seen', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 35, bed_no: 5 },
  { patient_id: 'ED013', esi: 3, age: 45, arrivalmode: 2, arrivalhour_bin: 5, insurance_status: 2, n_edvisits: 3, n_admissions: 0, triage_vital_hr: 126, triage_vital_sbp: 130, triage_vital_rr: 22, triage_vital_o2: 99, triage_vital_temp: 99.4, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 13:00', time_in_ed_minutes: 300, current_status: 'being_seen', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 36, bed_no: 6 },
  { patient_id: 'ED014', esi: 4, age: 46, arrivalmode: 6, arrivalhour_bin: 4, insurance_status: 2, n_edvisits: 4, n_admissions: 0, triage_vital_hr: 114, triage_vital_sbp: 144, triage_vital_rr: 18, triage_vital_o2: 98, triage_vital_temp: 98, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 10:00', time_in_ed_minutes: 480, current_status: 'being_seen', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 29, bed_no: 7 },
  { patient_id: 'ED015', esi: 3, age: 46, arrivalmode: 2, arrivalhour_bin: 6, insurance_status: 2, n_edvisits: 3, n_admissions: 0, triage_vital_hr: 97, triage_vital_sbp: 127, triage_vital_rr: 17, triage_vital_o2: 99, triage_vital_temp: 98.2, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 16:00', time_in_ed_minutes: 120, current_status: 'being_seen', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 41, bed_no: 8 },
  { patient_id: 'ED016', esi: 3, age: 50, arrivalmode: 2, arrivalhour_bin: 6, insurance_status: 1, n_edvisits: 1, n_admissions: 0, triage_vital_hr: 78, triage_vital_sbp: 120, triage_vital_rr: 18, triage_vital_o2: 99, triage_vital_temp: 99, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 16:00', time_in_ed_minutes: 120, current_status: 'being_seen', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 42, bed_no: 9 },
  { patient_id: 'ED017', esi: 4, age: 52, arrivalmode: 2, arrivalhour_bin: 3, insurance_status: 1, n_edvisits: 3, n_admissions: 0, triage_vital_hr: 70, triage_vital_sbp: 107, triage_vital_rr: 17, triage_vital_o2: 98, triage_vital_temp: 98.3, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 07:00', time_in_ed_minutes: 660, current_status: 'being_seen', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 27, bed_no: 10 },
  { patient_id: 'ED018', esi: 3, age: 35, arrivalmode: 2, arrivalhour_bin: 3, insurance_status: 1, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 83, triage_vital_sbp: 146, triage_vital_rr: 17, triage_vital_o2: 98, triage_vital_temp: 98, cc_chestpain: 1, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 07:00', time_in_ed_minutes: 660, current_status: 'being_seen', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 26, bed_no: 11 },
  { patient_id: 'ED019', esi: 2, age: 49, arrivalmode: 1, arrivalhour_bin: 5, insurance_status: 1, n_edvisits: 2, n_admissions: 1, triage_vital_hr: 76, triage_vital_sbp: 116, triage_vital_rr: 18, triage_vital_o2: 99, triage_vital_temp: 98.1, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 13:00', time_in_ed_minutes: 300, current_status: 'being_seen', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 37, bed_no: 12 },
  { patient_id: 'ED020', esi: 4, age: 31, arrivalmode: 2, arrivalhour_bin: 4, insurance_status: 2, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 71, triage_vital_sbp: 122, triage_vital_rr: 18, triage_vital_o2: 99, triage_vital_temp: 98.9, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 10:00', time_in_ed_minutes: 480, current_status: 'being_seen', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 28, bed_no: 13 },
  { patient_id: 'ED021', esi: 2, age: 32, arrivalmode: 6, arrivalhour_bin: 6, insurance_status: 2, n_edvisits: 1, n_admissions: 0, triage_vital_hr: 86, triage_vital_sbp: 117, triage_vital_rr: 18, triage_vital_o2: 98, triage_vital_temp: 96.6, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 1, arrival_timestamp: '04-01-2026 16:00', time_in_ed_minutes: 120, current_status: 'being_seen', predicted_admission_risk: 0.8, risk_level: 'High', recommended_priority_rank: 7, bed_no: 14 },
  { patient_id: 'ED022', esi: 3, age: 33, arrivalmode: 1, arrivalhour_bin: 2, insurance_status: 2, n_edvisits: 1, n_admissions: 1, triage_vital_hr: 88, triage_vital_sbp: 130, triage_vital_rr: 16, triage_vital_o2: 99, triage_vital_temp: 98.9, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 04:00', time_in_ed_minutes: 840, current_status: 'being_seen', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 23, bed_no: 15 },
  { patient_id: 'ED023', esi: 4, age: 41, arrivalmode: 6, arrivalhour_bin: 5, insurance_status: 1, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 89, triage_vital_sbp: 150, triage_vital_rr: 16, triage_vital_o2: 97, triage_vital_temp: 99.8, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 13:00', time_in_ed_minutes: 300, current_status: 'being_seen', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 38, bed_no: 16 },
  { patient_id: 'ED024', esi: 3, age: 21, arrivalmode: 6, arrivalhour_bin: 5, insurance_status: 1, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 100, triage_vital_sbp: 130, triage_vital_rr: 16, triage_vital_o2: 99, triage_vital_temp: 97.3, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 13:00', time_in_ed_minutes: 300, current_status: 'being_seen', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 39, bed_no: 17 },
  { patient_id: 'ED025', esi: 3, age: 22, arrivalmode: 2, arrivalhour_bin: 1, insurance_status: 1, n_edvisits: 1, n_admissions: 0, triage_vital_hr: 106, triage_vital_sbp: 103, triage_vital_rr: 16, triage_vital_o2: 97, triage_vital_temp: 98.2, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 01:00', time_in_ed_minutes: 1020, current_status: 'being_seen', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 22, bed_no: 18 },
  { patient_id: 'ED026', esi: 3, age: 56, arrivalmode: 7, arrivalhour_bin: 5, insurance_status: 3, n_edvisits: 1, n_admissions: 1, triage_vital_hr: 82, triage_vital_sbp: 178, triage_vital_rr: 14, triage_vital_o2: 98, triage_vital_temp: 97.4, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 1, arrival_timestamp: '04-01-2026 13:00', time_in_ed_minutes: 300, current_status: 'being_seen', predicted_admission_risk: 0.8, risk_level: 'High', recommended_priority_rank: 8, bed_no: 19 },
  { patient_id: 'ED027', esi: 4, age: 20, arrivalmode: 2, arrivalhour_bin: 3, insurance_status: 1, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 86, triage_vital_sbp: 117, triage_vital_rr: 18, triage_vital_o2: 99, triage_vital_temp: 98, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 07:00', time_in_ed_minutes: 660, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 21, bed_no: null },
  { patient_id: 'ED028', esi: 4, age: 21, arrivalmode: 2, arrivalhour_bin: 6, insurance_status: 1, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 109, triage_vital_sbp: 123, triage_vital_rr: 18, triage_vital_o2: 98, triage_vital_temp: 99.1, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 16:00', time_in_ed_minutes: 120, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 43, bed_no: null },
  { patient_id: 'ED029', esi: 2, age: 75, arrivalmode: 2, arrivalhour_bin: 1, insurance_status: 3, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 60, triage_vital_sbp: 98, triage_vital_rr: 18, triage_vital_o2: 95, triage_vital_temp: 98.9, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 01:00', time_in_ed_minutes: 1020, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 20, bed_no: null },
  { patient_id: 'ED030', esi: 3, age: 24, arrivalmode: 1, arrivalhour_bin: 3, insurance_status: 2, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 104, triage_vital_sbp: 131, triage_vital_rr: 18, triage_vital_o2: 98, triage_vital_temp: 97.5, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 1, arrival_timestamp: '04-01-2026 07:00', time_in_ed_minutes: 660, current_status: 'being_seen', predicted_admission_risk: 0.8, risk_level: 'High', recommended_priority_rank: 4, bed_no: 20 },
  { patient_id: 'ED031', esi: 3, age: 25, arrivalmode: 6, arrivalhour_bin: 3, insurance_status: 2, n_edvisits: 1, n_admissions: 1, triage_vital_hr: 88, triage_vital_sbp: 135, triage_vital_rr: 18, triage_vital_o2: 99, triage_vital_temp: 97.8, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 07:00', time_in_ed_minutes: 660, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 19, bed_no: null },
  { patient_id: 'ED032', esi: 2, age: 25, arrivalmode: 2, arrivalhour_bin: 3, insurance_status: 2, n_edvisits: 2, n_admissions: 1, triage_vital_hr: 134, triage_vital_sbp: 122, triage_vital_rr: 16, triage_vital_o2: 99, triage_vital_temp: 98.3, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 07:00', time_in_ed_minutes: 660, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 18, bed_no: null },
  { patient_id: 'ED033', esi: 3, age: 26, arrivalmode: 6, arrivalhour_bin: 6, insurance_status: 2, n_edvisits: 2, n_admissions: 0, triage_vital_hr: 110, triage_vital_sbp: 120, triage_vital_rr: 16, triage_vital_o2: 97, triage_vital_temp: 97, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 1, arrival_timestamp: '04-01-2026 16:00', time_in_ed_minutes: 120, current_status: 'being_seen', predicted_admission_risk: 0.8, risk_level: 'High', recommended_priority_rank: 9, bed_no: 21 },
  { patient_id: 'ED034', esi: 2, age: 62, arrivalmode: 1, arrivalhour_bin: 4, insurance_status: 2, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 77, triage_vital_sbp: 87, triage_vital_rr: 17, triage_vital_o2: 94, triage_vital_temp: 98.3, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 10:00', time_in_ed_minutes: 480, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 17, bed_no: null },
  { patient_id: 'ED035', esi: 2, age: 62, arrivalmode: 1, arrivalhour_bin: 1, insurance_status: 2, n_edvisits: 1, n_admissions: 0, triage_vital_hr: 84, triage_vital_sbp: 109, triage_vital_rr: 18, triage_vital_o2: 95, triage_vital_temp: 97.8, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 01:00', time_in_ed_minutes: 1020, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 16, bed_no: null },
  { patient_id: 'ED036', esi: 2, age: 62, arrivalmode: 1, arrivalhour_bin: 4, insurance_status: 2, n_edvisits: 2, n_admissions: 0, triage_vital_hr: 72, triage_vital_sbp: 71, triage_vital_rr: 16, triage_vital_o2: 96, triage_vital_temp: 97.6, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 1, arrival_timestamp: '04-01-2026 10:00', time_in_ed_minutes: 480, current_status: 'being_seen', predicted_admission_risk: 0.8, risk_level: 'High', recommended_priority_rank: 5, bed_no: 22 },
  { patient_id: 'ED037', esi: 2, age: 75, arrivalmode: 2, arrivalhour_bin: 4, insurance_status: 1, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 72, triage_vital_sbp: 144, triage_vital_rr: 18, triage_vital_o2: 98, triage_vital_temp: 98, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 1, arrival_timestamp: '04-01-2026 10:00', time_in_ed_minutes: 480, current_status: 'being_seen', predicted_admission_risk: 0.8, risk_level: 'High', recommended_priority_rank: 2, bed_no: 23 },
  { patient_id: 'ED038', esi: 4, age: 27, arrivalmode: 2, arrivalhour_bin: 1, insurance_status: 1, n_edvisits: 1, n_admissions: 0, triage_vital_hr: 79, triage_vital_sbp: 135, triage_vital_rr: 16, triage_vital_o2: 98, triage_vital_temp: 98, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 01:00', time_in_ed_minutes: 1020, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 15, bed_no: null },
  { patient_id: 'ED039', esi: 4, age: 54, arrivalmode: 2, arrivalhour_bin: 5, insurance_status: 2, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 96, triage_vital_sbp: 136, triage_vital_rr: 16, triage_vital_o2: 98, triage_vital_temp: 97.8, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 13:00', time_in_ed_minutes: 300, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 14, bed_no: null },
  { patient_id: 'ED040', esi: 2, age: 64, arrivalmode: 2, arrivalhour_bin: 5, insurance_status: 1, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 103, triage_vital_sbp: 113, triage_vital_rr: 16, triage_vital_o2: 96, triage_vital_temp: 98.8, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 1, arrival_timestamp: '04-01-2026 13:00', time_in_ed_minutes: 300, current_status: 'being_seen', predicted_admission_risk: 0.8, risk_level: 'High', recommended_priority_rank: 10, bed_no: 24 },
  { patient_id: 'ED043', esi: 3, age: 23, arrivalmode: 2, arrivalhour_bin: 4, insurance_status: 1, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 102, triage_vital_sbp: 153, triage_vital_rr: 16, triage_vital_o2: 98, triage_vital_temp: 98.8, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 10:00', time_in_ed_minutes: 480, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 11, bed_no: null },
  { patient_id: 'ED044', esi: 3, age: 91, arrivalmode: 2, arrivalhour_bin: 3, insurance_status: 3, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 87, triage_vital_sbp: 143, triage_vital_rr: 20, triage_vital_o2: 96, triage_vital_temp: 97.8, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 1, arrival_timestamp: '04-01-2026 07:00', time_in_ed_minutes: 660, current_status: 'being_seen', predicted_admission_risk: 0.8, risk_level: 'High', recommended_priority_rank: 11, bed_no: 25 },
  { patient_id: 'ED045', esi: 3, age: 67, arrivalmode: 1, arrivalhour_bin: 4, insurance_status: 3, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 89, triage_vital_sbp: 183, triage_vital_rr: 16, triage_vital_o2: 98, triage_vital_temp: 97.7, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 10:00', time_in_ed_minutes: 480, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 10, bed_no: null },
  { patient_id: 'ED046', esi: 4, age: 37, arrivalmode: 6, arrivalhour_bin: 5, insurance_status: 2, n_edvisits: 0, n_admissions: 0, triage_vital_hr: 82, triage_vital_sbp: 114, triage_vital_rr: 18, triage_vital_o2: 97, triage_vital_temp: 98, cc_chestpain: 0, cc_shortnessofbreath: 0, cc_alteredmentalstatus: 0, disposition: 2, arrival_timestamp: '04-01-2026 13:00', time_in_ed_minutes: 300, current_status: 'waiting', predicted_admission_risk: 0.25, risk_level: 'Low', recommended_priority_rank: 9, bed_no: null },
];
